#!/bin/bash
# Wrapper for cmc

call=$1
DIR="/usr/share/cmc/prog"

if [ "$call" == "--compile" ]; then
	python $DIR/build.py
elif [ "$call" == "--sync" ]; then
	python $DIR/sync.py
elif [ "$call" == "--download" ]; then
	python $DIR/dl_dialog.py
else
	python $DIR/cmcompiler.py
fi
